// TODO(assets): remplacer ces fichiers par les visuels définitifs
// (mêmes noms, même dossier assets/images/lesson-steps/) — aucun
// changement de code requis ailleurs, seulement le remplacement des
// fichiers. La clé (image_key) est fournie par le backend ; si une
// leçon renvoie une clé absente de cette table, LessonStepCard masque
// simplement l'étape correspondante plutôt que de planter.
export const LESSON_STEP_IMAGES: Record<string, number> = {
  bleeding_protect: require('../../assets/images/lesson-steps/bleeding_protect.jpg'),
  bleeding_compress: require('../../assets/images/lesson-steps/bleeding_compress.jpg'),
  bleeding_maintain: require('../../assets/images/lesson-steps/bleeding_maintain.jpg'),
  bleeding_no_elevation: require('../../assets/images/lesson-steps/bleeding_no_elevation.jpg'),
  bleeding_no_distance_pressure: require('../../assets/images/lesson-steps/bleeding_no_distance_pressure.jpg'),
  bleeding_direct_pressure_only: require('../../assets/images/lesson-steps/bleeding_direct_pressure_only.jpg'),
  bleeding_tourniquet: require('../../assets/images/lesson-steps/bleeding_tourniquet.jpg'),
  bleeding_internal: require('../../assets/images/lesson-steps/bleeding_internal.jpg'),
  bleeding_shock: require('../../assets/images/lesson-steps/bleeding_shock.jpg'),
  bleeding_nosebleed: require('../../assets/images/lesson-steps/bleeding_nosebleed.jpg'),
  choking_recognize: require('../../assets/images/lesson-steps/choking_recognize.jpg'),
  choking_position: require('../../assets/images/lesson-steps/choking_position.jpg'),
  choking_back_blows: require('../../assets/images/lesson-steps/choking_back_blows.jpg'),
  choking_abdominal_thrusts: require('../../assets/images/lesson-steps/choking_abdominal_thrusts.jpg'),
  choking_alternate: require('../../assets/images/lesson-steps/choking_alternate.jpg'),
  choking_stop: require('../../assets/images/lesson-steps/choking_stop.jpg'),
  choking_infant_back_blows: require('../../assets/images/lesson-steps/choking_infant_back_blows.jpg'),
  choking_infant_chest_thrusts: require('../../assets/images/lesson-steps/choking_infant_chest_thrusts.jpg'),
  malaise_check: require('../../assets/images/lesson-steps/malaise_check.jpg'),
  malaise_position_seated: require('../../assets/images/lesson-steps/malaise_position_seated.jpg'),
  malaise_position_lying: require('../../assets/images/lesson-steps/malaise_position_lying.jpg'),
  malaise_fast: require('../../assets/images/lesson-steps/malaise_fast.jpg'),
  malaise_befast: require('../../assets/images/lesson-steps/malaise_befast.jpg'),
  malaise_cardiac: require('../../assets/images/lesson-steps/malaise_cardiac.jpg'),
  cardiac_recognize: require('../../assets/images/lesson-steps/cardiac_recognize.jpg'),
  cardiac_check_reaction: require('../../assets/images/lesson-steps/cardiac_check_reaction.jpg'),
  cardiac_check_breathing: require('../../assets/images/lesson-steps/cardiac_check_breathing.jpg'),
  cardiac_call: require('../../assets/images/lesson-steps/cardiac_call.jpg'),
  cardiac_aed: require('../../assets/images/lesson-steps/cardiac_aed.jpg'),
  cardiac_hand_position: require('../../assets/images/lesson-steps/cardiac_hand_position.jpg'),
  cardiac_massage: require('../../assets/images/lesson-steps/cardiac_massage.jpg'),
  cardiac_compressions: require('../../assets/images/lesson-steps/cardiac_compressions.jpg'),
  drowning_recognize: require('../../assets/images/lesson-steps/drowning_recognize.jpg'),
  drowning_secure: require('../../assets/images/lesson-steps/drowning_secure.jpg'),
  drowning_alert: require('../../assets/images/lesson-steps/drowning_alert.jpg'),
  drowning_extract: require('../../assets/images/lesson-steps/drowning_extract.jpg'),
  drowning_breaths_compressions: require('../../assets/images/lesson-steps/drowning_breaths_compressions.jpg'),
  recovery_position_kneel: require('../../assets/images/lesson-steps/recovery_position_kneel.jpg'),
  recovery_position_arm: require('../../assets/images/lesson-steps/recovery_position_arm.jpg'),
  recovery_position_roll: require('../../assets/images/lesson-steps/recovery_position_roll.jpg'),
  recovery_position_adjust: require('../../assets/images/lesson-steps/recovery_position_adjust.jpg'),
  recovery_position_final: require('../../assets/images/lesson-steps/recovery_position_final.jpg'),
  burn_severity: require('../../assets/images/lesson-steps/burn_severity.jpg'),
  burn_cool: require('../../assets/images/lesson-steps/burn_cool.jpg'),
  burn_myths: require('../../assets/images/lesson-steps/burn_myths.jpg'),
  burn_remove_jewelry: require('../../assets/images/lesson-steps/burn_remove_jewelry.jpg'),
  burn_stuck_clothing: require('../../assets/images/lesson-steps/burn_stuck_clothing.jpg'),
  burn_cover: require('../../assets/images/lesson-steps/burn_cover.jpg'),
  avc_position_call: require('../../assets/images/lesson-steps/avc_position_call.jpg'),
  avc_pls_reminder: require('../../assets/images/lesson-steps/avc_pls_reminder.jpg'),
  avc_fast_test: require('../../assets/images/lesson-steps/avc_fast_test.jpg'),
  avc_befast_test: require('../../assets/images/lesson-steps/avc_befast_test.jpg'),
  general_principles_protect: require('../../assets/images/lesson-steps/general_principles_protect.jpg'),
  general_principles_alert: require('../../assets/images/lesson-steps/general_principles_alert.jpg'),
  general_principles_act: require('../../assets/images/lesson-steps/general_principles_act.jpg'),
};
